> docker-software-delivery@1.0.0 start /app
> node ./bin/www
NODE_ENV: production
> docker-software-delivery@1.0.0 start /app
> node ./bin/www
NODE_ENV: production
/app/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 192.168.160.2:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  name: 'MongoError'
}]
    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:400:28)
    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:520:26)
    at Connection.emit...
    at /app/app.js:24:10
    at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /app/node_modules/mongodb/lib/mongo_client.js:418:11
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 192.168.160.2:27017
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
    name: 'MongoError'
  }]
      at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
      at Pool.emit (events.js:400:28)
      at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
      at Object.onceWrapper (events.js:520:26)
      at Connection.emit (events.js:400:28)
      at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
      at Object.onceWrapper (events.js:520:26)
      at Socket.emit (events.js:400:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3),
  operator: '=='
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-11-02T06_48_33_760Z-debug.log
/app/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 192.168.160.2:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  name: 'MongoError'
}]
    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:400:28)
    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:520:26)
    at Connection.emit...
    at /app/app.js:24:10
    at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /app/node_modules/mongodb/lib/mongo_client.js:418:11
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: null,
  expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 192.168.160.2:27017
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
    name: 'MongoError'
  }]
      at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
      at Pool.emit (events.js:400:28)
      at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
      at Object.onceWrapper (events.js:520:26)
      at Connection.emit (events.js:400:28)
      at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
      at Object.onceWrapper (events.js:520:26)
      at Socket.emit (events.js:400:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3),
  operator: '=='
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-11-02T06_48_34_878Z-debug.log
> docker-software-delivery@1.0.0 start /app
> node ./bin/www
NODE_ENV: production
Connected to database
GET / 200 245.502 ms - 788
GET /javascripts/dist/dist.min.js 200 4.085 ms - 186999
GET /stylesheets/style.css 200 19.342 ms - 519
GET /javascripts/dist/dist.min.js 200 1.385 ms - 186999
GET /api 304 8.076 ms - -
POST /api 201 76.643 ms - 50
POST /api 201 8.789 ms - 51
POST /api 201 7.088 ms - 53
